// Writes the illustration library: public/illustrations/<id>.svg and src/engine/illustrations.ts (the index).
// Usage: node scripts/illustrations/build.cjs
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..", "..");
const categories = fs
  .readdirSync(__dirname)
  .filter((f) => f.endsWith(".cjs") && f !== "build.cjs" && !f.startsWith("_"))
  .map((f) => f.replace(".cjs", ""))
  .sort();

const outDir = path.join(root, "public", "illustrations");
fs.mkdirSync(outDir, { recursive: true });
for (const f of fs.readdirSync(outDir)) if (f.endsWith(".svg")) fs.unlinkSync(path.join(outDir, f));

const entries = [];
for (const category of categories) {
  const items = require(path.join(__dirname, `${category}.cjs`));
  for (const [id, item] of Object.entries(items)) {
    if (entries.some((e) => e.id === id)) throw new Error(`duplicate illustration id ${id}`);
    const svg = item.svg.replace(/\n\s*/g, "\n").trim() + "\n";
    if (/—/.test(svg + item.name + item.tags)) throw new Error(`em dash in ${id}`);
    fs.writeFileSync(path.join(outDir, `${id}.svg`), svg);
    entries.push({ id, name: item.name, category, tags: item.tags });
  }
}

const lines = entries.map((e) => `  { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, category: ${JSON.stringify(e.category)}, tags: ${JSON.stringify(e.tags)} },`);
const ts = `// Generated by scripts/illustrations/build.cjs. Do not edit by hand: change the category files there.
// The animated SVGs themselves are in public/illustrations/<id>.svg.

export interface Illustration {
  id: string;
  name: string;
  category: string;
  /** Words it can illustrate, for search and for the AI to pick. */
  tags: string;
}

export const ILLUSTRATIONS: Illustration[] = [
${lines.join("\n")}
];

export const ILLUSTRATION_CATEGORIES = ${JSON.stringify(categories)} as const;

/** The best library illustration for a topic ("dentist", "sales growth"), or undefined. */
export function findIllustration(query: string): Illustration | undefined {
  const words = query.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2);
  if (!words.length) return undefined;
  let best: Illustration | undefined;
  let bestScore = 0;
  for (const ill of ILLUSTRATIONS) {
    if (ill.id === query.trim().toLowerCase()) return ill;
    const tags = \` \${ill.id} \${ill.name.toLowerCase()} \${ill.tags} \`;
    let score = 0;
    for (const w of words) {
      if (tags.includes(\` \${w} \`)) score += 3;
      else if (tags.includes(w)) score += 1;
      else if (w.endsWith("s") && tags.includes(\` \${w.slice(0, -1)} \`)) score += 2;
    }
    if (score > bestScore) {
      best = ill;
      bestScore = score;
    }
  }
  return bestScore >= 2 ? best : undefined;
}

const STOP = new Set(["the", "and", "for", "with", "our", "your", "set", "icon", "illustration", "picture", "drawing", "animated", "of", "a", "an"]);

/** True when every meaningful word of the topic is in the illustration's tags (not just a loose match). */
export function coversTopic(ill: Illustration, query: string): boolean {
  if (ill.id === query.trim().toLowerCase().replace(/^lib:/, "")) return true;
  const tags = \` \${ill.id} \${ill.name.toLowerCase()} \${ill.tags} \`;
  const words = query.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2 && !STOP.has(w));
  return words.length > 0 && words.every((w) => tags.includes(\` \${w} \`) || (w.endsWith("s") && tags.includes(\` \${w.slice(0, -1)} \`)) || tags.includes(\` \${w}s \`));
}
`;
fs.writeFileSync(path.join(root, "src", "engine", "illustrations.ts"), ts);
console.log(`${entries.length} illustrations in ${categories.length} categories`);
