// Generated by scripts/illustrations/build.cjs. Do not edit by hand: change the category files there.
// The animated SVGs themselves are in public/illustrations/<id>.svg.

export interface Illustration {
  id: string;
  name: string;
  category: string;
  /** Words it can illustrate, for search and for the AI to pick. */
  tags: string;
}

export const ILLUSTRATIONS: Illustration[] = [
  { id: "barchart", name: "Growing bar chart", category: "business", tags: "bar chart growth sales revenue statistics data report increase results analytics performance kpi" },
  { id: "linechart", name: "Line graph", category: "business", tags: "line graph chart trend growth stock market statistics analytics progress data dashboard" },
  { id: "piechart", name: "Pie chart", category: "business", tags: "pie chart share percentage market share budget breakdown survey statistics proportion" },
  { id: "money", name: "Money and coins", category: "business", tags: "money cash coins finance savings income profit salary budget payment wealth dollars economy" },
  { id: "piggybank", name: "Piggy bank", category: "business", tags: "piggy bank savings save money budget finance deposit investment kids banking" },
  { id: "target", name: "Target and arrow", category: "business", tags: "target goal aim objective focus strategy success mission accuracy bullseye marketing" },
  { id: "trophy", name: "Trophy", category: "business", tags: "trophy award winner champion achievement success prize first place victory best competition" },
  { id: "rocket", name: "Rocket launch", category: "business", tags: "rocket launch startup growth space innovation boost fast launch product mission" },
  { id: "lightbulb", name: "Idea light bulb", category: "business", tags: "idea light bulb innovation creativity brainstorm inspiration solution insight think invention tip" },
  { id: "gears", name: "Turning gears", category: "business", tags: "gears settings process system engineering mechanism workflow automation operations teamwork machine" },
  { id: "calendar", name: "Calendar", category: "business", tags: "calendar date schedule deadline appointment plan event month booking agenda time" },
  { id: "clock", name: "Clock", category: "business", tags: "clock time hours deadline punctual schedule minutes waiting timing productivity" },
  { id: "hourglass", name: "Hourglass", category: "business", tags: "hourglass time waiting patience deadline countdown loading sand timer" },
  { id: "presentation", name: "Presentation board", category: "business", tags: "presentation board meeting slides report teaching seminar training pitch lecture chart whiteboard" },
  { id: "handshake", name: "Handshake", category: "business", tags: "handshake deal partnership agreement cooperation contract business trust collaboration welcome" },
  { id: "team", name: "Team", category: "business", tags: "team people group staff colleagues employees community teamwork users audience customers hr" },
  { id: "briefcase", name: "Briefcase", category: "business", tags: "briefcase business job work career office employment professional portfolio corporate" },
  { id: "shoppingcart", name: "Shopping cart", category: "business", tags: "shopping cart ecommerce online store buy purchase retail sale checkout customer order" },
  { id: "bank", name: "Bank", category: "business", tags: "bank finance loan banking institution money credit investment financial building savings" },
  { id: "creditcard", name: "Credit card payment", category: "business", tags: "credit card payment pay purchase bank card transaction checkout debit wallet fintech" },
  { id: "puzzle", name: "Puzzle pieces", category: "business", tags: "puzzle pieces solution fit strategy problem solving integration teamwork match strategy connect" },
  { id: "growth", name: "Growth stairs", category: "business", tags: "growth steps progress career ladder improvement stairs success levels development milestones" },
  { id: "chat", name: "Chat bubbles", category: "communication", tags: "chat messages conversation talk support customer service texting communication feedback discussion" },
  { id: "email", name: "Email envelope", category: "communication", tags: "email mail envelope message newsletter inbox letter contact send marketing communication" },
  { id: "megaphone", name: "Megaphone announcement", category: "communication", tags: "megaphone announcement marketing promotion advertising news campaign loudspeaker shout broadcast attention" },
  { id: "socialmedia", name: "Social media likes", category: "communication", tags: "social media likes followers engagement instagram facebook influencer marketing viral content reactions" },
  { id: "videocall", name: "Video call", category: "communication", tags: "video call meeting online conference remote work zoom webinar camera streaming" },
  { id: "newspaper", name: "News", category: "communication", tags: "news newspaper article media press journalism headlines report blog update information" },
  { id: "notification", name: "Notification bell", category: "communication", tags: "notification bell alert reminder alarm update subscribe ring attention" },
  { id: "gift", name: "Gift box", category: "communication", tags: "gift present box surprise reward bonus birthday celebration giveaway offer discount holiday" },
  { id: "book", name: "Open book", category: "education", tags: "book reading study learning education library knowledge literature story school novel" },
  { id: "graduation", name: "Graduation cap", category: "education", tags: "graduation cap degree university college diploma graduate education school achievement academic student" },
  { id: "pencil", name: "Pencil writing", category: "education", tags: "pencil write writing notes draw drawing homework sketch design edit exam school" },
  { id: "microscope", name: "Microscope", category: "education", tags: "microscope science laboratory research biology lab experiment scientist medicine discovery study" },
  { id: "atom", name: "Atom", category: "education", tags: "atom science physics chemistry nuclear energy molecule research electron quantum" },
  { id: "flask", name: "Chemistry flask", category: "education", tags: "flask chemistry lab experiment science beaker potion research chemical test reaction" },
  { id: "calculator", name: "Calculator", category: "education", tags: "calculator math accounting finance numbers calculate tax budget arithmetic sums" },
  { id: "telescope", name: "Telescope and stars", category: "education", tags: "telescope astronomy stars space vision future explore discovery night sky science" },
  { id: "abcblocks", name: "ABC blocks", category: "education", tags: "abc blocks alphabet kids children preschool kindergarten learning letters toys early education" },
  { id: "studentdesk", name: "Student at desk", category: "education", tags: "student studying desk homework exam learning online class school education laptop" },
  { id: "teeth", name: "Teeth set", category: "health", tags: "teeth dentist dental mouth smile jaw oral hygiene orthodontist" },
  { id: "tooth", name: "Happy tooth", category: "health", tags: "tooth dentist dental molar clean healthy smile cavity kids" },
  { id: "toothbrush", name: "Toothbrush and paste", category: "health", tags: "toothbrush toothpaste brushing dentist dental hygiene clean teeth routine" },
  { id: "heart", name: "Beating heart", category: "health", tags: "heart cardiology health love pulse heartbeat cardio medical care wellness" },
  { id: "brain", name: "Brain and ideas", category: "health", tags: "brain mind neurology thinking memory psychology mental health intelligence learning neuroscience" },
  { id: "lungs", name: "Breathing lungs", category: "health", tags: "lungs breathing respiratory asthma pulmonary oxygen air chest health smoking" },
  { id: "stethoscope", name: "Stethoscope", category: "health", tags: "stethoscope doctor medical checkup clinic physician examination healthcare nurse" },
  { id: "pills", name: "Pills and capsules", category: "health", tags: "pills medicine capsule tablet pharmacy drug prescription treatment vitamins pharmacist" },
  { id: "dna", name: "DNA helix", category: "health", tags: "dna genetics biology science gene helix chromosome research laboratory biotech heredity" },
  { id: "virus", name: "Germ virus", category: "health", tags: "virus germ bacteria infection flu covid disease microbe immunity pathogen hygiene" },
  { id: "thermometer", name: "Thermometer", category: "health", tags: "thermometer fever temperature sick flu illness weather heat hot cold measure" },
  { id: "syringe", name: "Vaccine syringe", category: "health", tags: "syringe vaccine injection vaccination immunization shot needle medicine clinic" },
  { id: "hospital", name: "Hospital", category: "health", tags: "hospital clinic building healthcare emergency medical center doctor care" },
  { id: "firstaid", name: "First aid kit", category: "health", tags: "first aid kit emergency safety injury medical bandage help rescue" },
  { id: "eye", name: "Eye", category: "health", tags: "eye vision sight optometry eye care ophthalmology see watch observe" },
  { id: "bone", name: "Bone", category: "health", tags: "bone orthopedics skeleton fracture calcium joints x-ray physiotherapy" },
  { id: "plant", name: "Growing plant", category: "nature", tags: "plant growing seedling growth sprout garden nature environment sustainability eco green agriculture" },
  { id: "tree", name: "Tree in the wind", category: "nature", tags: "tree forest nature environment park outdoors oak ecology climate green woods" },
  { id: "sun", name: "Shining sun", category: "nature", tags: "sun sunny summer weather hot day sunshine solar energy light bright morning" },
  { id: "rain", name: "Rain cloud", category: "nature", tags: "rain cloud weather storm rainy water monsoon forecast climate umbrella precipitation" },
  { id: "recycle", name: "Recycling", category: "nature", tags: "recycle recycling environment eco waste reuse sustainability green zero waste circular planet" },
  { id: "earth", name: "Save the planet", category: "nature", tags: "earth planet environment climate change eco sustainability green world nature save protect" },
  { id: "waterdrop", name: "Water drop", category: "nature", tags: "water drop hydration drink clean water save water liquid rain aqua ripple" },
  { id: "mountain", name: "Mountain goal", category: "nature", tags: "mountain summit goal challenge adventure hiking peak climb achievement journey success outdoors" },
  { id: "flower", name: "Blooming flower", category: "nature", tags: "flower bloom spring garden beauty nature floral blossom gift women wellness" },
  { id: "snowflake", name: "Snowflake", category: "nature", tags: "snowflake snow winter cold ice frozen christmas season weather freeze" },
  { id: "solarpanel", name: "Solar panel", category: "nature", tags: "solar panel renewable energy clean power electricity sun green energy sustainability" },
  { id: "animals", name: "Cat and dog", category: "nature", tags: "pets animals cat dog veterinary vet pet care puppy kitten animal shelter" },
  { id: "airplane", name: "Airplane", category: "places", tags: "airplane plane flight travel trip vacation tourism airline flying international holiday journey" },
  { id: "car", name: "Car driving", category: "places", tags: "car driving vehicle transport automobile road trip commute traffic automotive delivery taxi" },
  { id: "truck", name: "Delivery truck", category: "places", tags: "truck delivery shipping logistics transport cargo courier freight supply chain order dispatch" },
  { id: "mappin", name: "Map location pin", category: "places", tags: "map location pin place address gps navigation destination local store find us directions" },
  { id: "house", name: "House", category: "places", tags: "house home real estate property mortgage family living rent buy apartment housing" },
  { id: "city", name: "City skyline", category: "places", tags: "city skyline buildings urban town downtown company office real estate metropolis skyscrapers" },
  { id: "coffee", name: "Coffee cup", category: "places", tags: "coffee cup cafe morning break drink tea hot beverage restaurant meeting relax energy" },
  { id: "food", name: "Healthy food", category: "places", tags: "food healthy eating nutrition diet salad fruit vegetables meal recipe restaurant cooking" },
  { id: "fitness", name: "Fitness dumbbell", category: "places", tags: "fitness gym dumbbell exercise workout health sports strength training weight lifting wellness" },
  { id: "music", name: "Music notes", category: "places", tags: "music notes song audio sound melody concert singing podcast entertainment listen" },
  { id: "camera", name: "Camera", category: "places", tags: "camera photo photography picture video film shoot media content creator snapshot" },
  { id: "play", name: "Video play button", category: "places", tags: "video play youtube streaming media film watch tutorial course content player movie" },
  { id: "checkmark", name: "Check mark", category: "symbols", tags: "check mark done complete yes correct approved success tick verified finished ok" },
  { id: "cross", name: "Cross mark", category: "symbols", tags: "cross wrong no mistake error incorrect avoid reject do not myth false" },
  { id: "warning", name: "Warning sign", category: "symbols", tags: "warning caution alert danger attention risk important notice hazard careful" },
  { id: "star", name: "Star rating", category: "symbols", tags: "star rating review favorite quality excellent best top rated feedback five stars award" },
  { id: "question", name: "Question mark", category: "symbols", tags: "question mark faq help ask quiz doubt unknown why curious query support" },
  { id: "arrowup", name: "Arrow up growth", category: "symbols", tags: "arrow up increase growth rise improvement boost trend profit higher gain progress" },
  { id: "arrowdown", name: "Arrow down decline", category: "symbols", tags: "arrow down decrease decline drop reduce fall loss cut lower cost reduction" },
  { id: "thumbsup", name: "Thumbs up", category: "symbols", tags: "thumbs up like good approve great job recommend positive agree yes" },
  { id: "percent", name: "Discount percent", category: "symbols", tags: "percent discount sale offer deal promotion price off coupon savings interest rate" },
  { id: "number1", name: "Number one medal", category: "symbols", tags: "number one first place medal winner best rank top champion gold leader" },
  { id: "happyface", name: "Happy customer", category: "symbols", tags: "happy smile satisfied customer joy positive feedback satisfaction emotion mood wellbeing" },
  { id: "sadface", name: "Sad face", category: "symbols", tags: "sad unhappy problem pain stress complaint frustration disappointed emotion negative" },
  { id: "loading", name: "Loading spinner", category: "symbols", tags: "loading progress waiting processing spinner working buffering in progress update" },
  { id: "quote", name: "Quote marks", category: "symbols", tags: "quote testimonial saying review opinion words speech citation interview feedback" },
  { id: "checklist", name: "Checklist", category: "symbols", tags: "checklist to do list tasks plan steps requirements agenda survey form clipboard items" },
  { id: "laptop", name: "Laptop with code", category: "technology", tags: "laptop computer coding software developer programming work online remote technology it web app" },
  { id: "smartphone", name: "Smartphone app", category: "technology", tags: "smartphone phone mobile app notification social media android iphone message device screen" },
  { id: "cloud", name: "Cloud upload", category: "technology", tags: "cloud upload storage backup sync saas online data hosting server download computing" },
  { id: "lock", name: "Security lock", category: "technology", tags: "lock security password privacy protection secure encryption login cybersecurity safe access" },
  { id: "shield", name: "Shield with check", category: "technology", tags: "shield protection security safe insurance antivirus guarantee trust verified defense privacy" },
  { id: "wifi", name: "Wi-Fi signal", category: "technology", tags: "wifi wireless internet signal connection network online hotspot connectivity broadband" },
  { id: "robot", name: "AI robot", category: "technology", tags: "robot ai artificial intelligence automation chatbot machine learning assistant bot future technology" },
  { id: "chip", name: "Computer chip", category: "technology", tags: "chip processor cpu semiconductor circuit hardware electronics microchip computing ai technology" },
  { id: "code", name: "Code brackets", category: "technology", tags: "code programming developer software html web development coding syntax script engineer" },
  { id: "database", name: "Database", category: "technology", tags: "database data storage server records sql big data backend information analytics warehouse" },
  { id: "magnifier", name: "Search magnifier", category: "technology", tags: "search magnifier find research investigate seo discover analysis explore zoom inspect" },
  { id: "battery", name: "Charging battery", category: "technology", tags: "battery charging energy power electric ev charge level electricity sustainability" },
  { id: "bug", name: "Software bug", category: "technology", tags: "bug software error debug testing issue fix glitch qa problem malware" },
  { id: "globe", name: "Spinning globe", category: "technology", tags: "globe world earth international global travel geography planet countries worldwide map" },
];

export const ILLUSTRATION_CATEGORIES = ["business","communication","education","health","nature","places","symbols","technology"] as const;

/** The best library illustration for a topic ("dentist", "sales growth"), or undefined. */
export function findIllustration(query: string): Illustration | undefined {
  const words = query.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2);
  if (!words.length) return undefined;
  let best: Illustration | undefined;
  let bestScore = 0;
  for (const ill of ILLUSTRATIONS) {
    if (ill.id === query.trim().toLowerCase()) return ill;
    const tags = ` ${ill.id} ${ill.name.toLowerCase()} ${ill.tags} `;
    let score = 0;
    for (const w of words) {
      if (tags.includes(` ${w} `)) score += 3;
      else if (tags.includes(w)) score += 1;
      else if (w.endsWith("s") && tags.includes(` ${w.slice(0, -1)} `)) score += 2;
    }
    if (score > bestScore) {
      best = ill;
      bestScore = score;
    }
  }
  return bestScore >= 2 ? best : undefined;
}

const STOP = new Set(["the", "and", "for", "with", "our", "your", "set", "icon", "illustration", "picture", "drawing", "animated", "of", "a", "an"]);

/** True when every meaningful word of the topic is in the illustration's tags (not just a loose match). */
export function coversTopic(ill: Illustration, query: string): boolean {
  if (ill.id === query.trim().toLowerCase().replace(/^lib:/, "")) return true;
  const tags = ` ${ill.id} ${ill.name.toLowerCase()} ${ill.tags} `;
  const words = query.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2 && !STOP.has(w));
  return words.length > 0 && words.every((w) => tags.includes(` ${w} `) || (w.endsWith("s") && tags.includes(` ${w.slice(0, -1)} `)) || tags.includes(` ${w}s `));
}
