// Emoji stickers: Twemoji graphics (https://github.com/jdecked/twemoji), CC-BY 4.0.
// The SVG files are in public/stickers/<code>.svg, with the licence beside them.

export interface Sticker {
  code: string;
  char: string;
  name: string;
  group: "faces" | "gestures" | "hearts" | "symbols" | "objects" | "nature" | "food" | "travel";
}

export const STICKER_CREDIT = "Emoji graphics by Twemoji, licensed CC-BY 4.0";

export const STICKERS: Sticker[] = [
  // Faces
  { code: "1f600", char: "😀", name: "grinning", group: "faces" },
  { code: "1f602", char: "😂", name: "tears of joy", group: "faces" },
  { code: "1f923", char: "🤣", name: "rolling laughing", group: "faces" },
  { code: "1f60a", char: "😊", name: "smiling", group: "faces" },
  { code: "1f60d", char: "😍", name: "heart eyes", group: "faces" },
  { code: "1f929", char: "🤩", name: "star struck", group: "faces" },
  { code: "1f60e", char: "😎", name: "cool sunglasses", group: "faces" },
  { code: "1f914", char: "🤔", name: "thinking", group: "faces" },
  { code: "1f928", char: "🤨", name: "raised eyebrow", group: "faces" },
  { code: "1f610", char: "😐", name: "neutral", group: "faces" },
  { code: "1f644", char: "🙄", name: "eye roll", group: "faces" },
  { code: "1f62e", char: "😮", name: "surprised", group: "faces" },
  { code: "1f631", char: "😱", name: "screaming shocked", group: "faces" },
  { code: "1f622", char: "😢", name: "crying", group: "faces" },
  { code: "1f62d", char: "😭", name: "sobbing", group: "faces" },
  { code: "1f621", char: "😡", name: "angry", group: "faces" },
  { code: "1f92f", char: "🤯", name: "mind blown", group: "faces" },
  { code: "1f973", char: "🥳", name: "party", group: "faces" },
  { code: "1f634", char: "😴", name: "sleeping", group: "faces" },
  { code: "1f922", char: "🤢", name: "sick", group: "faces" },
  { code: "1f92b", char: "🤫", name: "shush quiet", group: "faces" },
  { code: "1f917", char: "🤗", name: "hug", group: "faces" },
  { code: "1f605", char: "😅", name: "sweat smile relief", group: "faces" },
  { code: "1f643", char: "🙃", name: "upside down", group: "faces" },
  { code: "1f47b", char: "👻", name: "ghost", group: "faces" },
  { code: "1f916", char: "🤖", name: "robot", group: "faces" },
  { code: "1f440", char: "👀", name: "eyes look", group: "faces" },
  // Gestures
  { code: "1f44d", char: "👍", name: "thumbs up", group: "gestures" },
  { code: "1f44e", char: "👎", name: "thumbs down", group: "gestures" },
  { code: "1f44f", char: "👏", name: "clapping", group: "gestures" },
  { code: "1f64c", char: "🙌", name: "raised hands celebrate", group: "gestures" },
  { code: "1f64f", char: "🙏", name: "please thanks pray", group: "gestures" },
  { code: "1f44b", char: "👋", name: "wave hello", group: "gestures" },
  { code: "1f44c", char: "👌", name: "ok", group: "gestures" },
  { code: "270c", char: "✌", name: "peace victory", group: "gestures" },
  { code: "1f91e", char: "🤞", name: "fingers crossed", group: "gestures" },
  { code: "1f4aa", char: "💪", name: "strong muscle", group: "gestures" },
  { code: "1f449", char: "👉", name: "point right", group: "gestures" },
  { code: "1f448", char: "👈", name: "point left", group: "gestures" },
  { code: "1f446", char: "👆", name: "point up", group: "gestures" },
  { code: "1f447", char: "👇", name: "point down", group: "gestures" },
  { code: "261d", char: "☝", name: "index up", group: "gestures" },
  { code: "1f91d", char: "🤝", name: "handshake deal", group: "gestures" },
  { code: "270d", char: "✍", name: "writing", group: "gestures" },
  // Hearts
  { code: "2764", char: "❤", name: "red heart love", group: "hearts" },
  { code: "1f9e1", char: "🧡", name: "orange heart", group: "hearts" },
  { code: "1f49b", char: "💛", name: "yellow heart", group: "hearts" },
  { code: "1f49a", char: "💚", name: "green heart", group: "hearts" },
  { code: "1f499", char: "💙", name: "blue heart", group: "hearts" },
  { code: "1f49c", char: "💜", name: "purple heart", group: "hearts" },
  { code: "1f5a4", char: "🖤", name: "black heart", group: "hearts" },
  { code: "1f494", char: "💔", name: "broken heart", group: "hearts" },
  { code: "1f496", char: "💖", name: "sparkling heart", group: "hearts" },
  // Symbols
  { code: "2705", char: "✅", name: "check done yes", group: "symbols" },
  { code: "274c", char: "❌", name: "cross wrong no", group: "symbols" },
  { code: "2714", char: "✔", name: "tick", group: "symbols" },
  { code: "2757", char: "❗", name: "exclamation important", group: "symbols" },
  { code: "2753", char: "❓", name: "question", group: "symbols" },
  { code: "26a0", char: "⚠", name: "warning", group: "symbols" },
  { code: "1f6ab", char: "🚫", name: "prohibited not allowed", group: "symbols" },
  { code: "2b50", char: "⭐", name: "star", group: "symbols" },
  { code: "1f31f", char: "🌟", name: "glowing star", group: "symbols" },
  { code: "2728", char: "✨", name: "sparkles new", group: "symbols" },
  { code: "1f4a5", char: "💥", name: "boom collision", group: "symbols" },
  { code: "1f4af", char: "💯", name: "hundred perfect", group: "symbols" },
  { code: "1f4a1", char: "💡", name: "idea light bulb tip", group: "symbols" },
  { code: "1f4ac", char: "💬", name: "speech bubble comment", group: "symbols" },
  { code: "1f4ad", char: "💭", name: "thought bubble", group: "symbols" },
  { code: "27a1", char: "➡", name: "arrow right", group: "symbols" },
  { code: "2b05", char: "⬅", name: "arrow left", group: "symbols" },
  { code: "2b06", char: "⬆", name: "arrow up", group: "symbols" },
  { code: "2b07", char: "⬇", name: "arrow down", group: "symbols" },
  { code: "1f504", char: "🔄", name: "repeat refresh", group: "symbols" },
  { code: "1f195", char: "🆕", name: "new", group: "symbols" },
  { code: "1f193", char: "🆓", name: "free", group: "symbols" },
  { code: "1f199", char: "🆙", name: "up", group: "symbols" },
  { code: "1f51d", char: "🔝", name: "top", group: "symbols" },
  { code: "1f534", char: "🔴", name: "red circle live record", group: "symbols" },
  { code: "1f7e2", char: "🟢", name: "green circle", group: "symbols" },
  { code: "1f3af", char: "🎯", name: "target goal", group: "symbols" },
  { code: "1f3c6", char: "🏆", name: "trophy winner", group: "symbols" },
  { code: "1f947", char: "🥇", name: "gold medal first", group: "symbols" },
  { code: "1f389", char: "🎉", name: "party popper celebrate", group: "symbols" },
  { code: "1f38a", char: "🎊", name: "confetti", group: "symbols" },
  { code: "1f381", char: "🎁", name: "gift present", group: "symbols" },
  { code: "1f514", char: "🔔", name: "bell notification subscribe", group: "symbols" },
  // Objects
  { code: "1f4f1", char: "📱", name: "phone mobile", group: "objects" },
  { code: "1f4bb", char: "💻", name: "laptop computer", group: "objects" },
  { code: "1f5b1", char: "🖱", name: "mouse click", group: "objects" },
  { code: "2328", char: "⌨", name: "keyboard", group: "objects" },
  { code: "1f4f7", char: "📷", name: "camera photo", group: "objects" },
  { code: "1f3a5", char: "🎥", name: "movie camera video", group: "objects" },
  { code: "1f3a4", char: "🎤", name: "microphone", group: "objects" },
  { code: "1f4e2", char: "📢", name: "loudspeaker announce", group: "objects" },
  { code: "1f4e3", char: "📣", name: "megaphone", group: "objects" },
  { code: "1f4cc", char: "📌", name: "pin", group: "objects" },
  { code: "1f4ce", char: "📎", name: "paperclip", group: "objects" },
  { code: "1f4c8", char: "📈", name: "chart up growth", group: "objects" },
  { code: "1f4c9", char: "📉", name: "chart down", group: "objects" },
  { code: "1f4b0", char: "💰", name: "money bag", group: "objects" },
  { code: "1f4b8", char: "💸", name: "money flying spend", group: "objects" },
  { code: "1f6d2", char: "🛒", name: "shopping cart", group: "objects" },
  { code: "1f511", char: "🔑", name: "key", group: "objects" },
  { code: "1f512", char: "🔒", name: "lock secure", group: "objects" },
  { code: "1f50d", char: "🔍", name: "search magnifier", group: "objects" },
  { code: "23f0", char: "⏰", name: "alarm clock time", group: "objects" },
  { code: "231b", char: "⌛", name: "hourglass waiting", group: "objects" },
  { code: "1f4c5", char: "📅", name: "calendar date", group: "objects" },
  { code: "1f4da", char: "📚", name: "books learn", group: "objects" },
  { code: "270f", char: "✏", name: "pencil edit", group: "objects" },
  { code: "1f6e0", char: "🛠", name: "tools build", group: "objects" },
  { code: "2699", char: "⚙", name: "gear settings", group: "objects" },
  { code: "1f680", char: "🚀", name: "rocket launch", group: "objects" },
  { code: "1f4e6", char: "📦", name: "package box delivery", group: "objects" },
  // Nature
  { code: "1f525", char: "🔥", name: "fire hot lit", group: "nature" },
  { code: "26a1", char: "⚡", name: "lightning fast", group: "nature" },
  { code: "2600", char: "☀", name: "sun", group: "nature" },
  { code: "1f319", char: "🌙", name: "moon night", group: "nature" },
  { code: "1f308", char: "🌈", name: "rainbow", group: "nature" },
  { code: "2744", char: "❄", name: "snowflake cold", group: "nature" },
  { code: "1f30a", char: "🌊", name: "wave ocean", group: "nature" },
  { code: "1f331", char: "🌱", name: "seedling grow", group: "nature" },
  { code: "1f338", char: "🌸", name: "blossom flower", group: "nature" },
  { code: "1f333", char: "🌳", name: "tree", group: "nature" },
  { code: "1f418", char: "🐘", name: "elephant", group: "nature" },
  { code: "1f431", char: "🐱", name: "cat", group: "nature" },
  { code: "1f436", char: "🐶", name: "dog", group: "nature" },
  { code: "1f98b", char: "🦋", name: "butterfly", group: "nature" },
  { code: "1f30d", char: "🌍", name: "globe world", group: "nature" },
  // Food
  { code: "2615", char: "☕", name: "coffee", group: "food" },
  { code: "1f355", char: "🍕", name: "pizza", group: "food" },
  { code: "1f354", char: "🍔", name: "burger", group: "food" },
  { code: "1f370", char: "🍰", name: "cake", group: "food" },
  { code: "1f34e", char: "🍎", name: "apple", group: "food" },
  { code: "1f964", char: "🥤", name: "drink cup", group: "food" },
  // Travel
  { code: "2708", char: "✈", name: "plane travel", group: "travel" },
  { code: "1f697", char: "🚗", name: "car", group: "travel" },
  { code: "1f3e0", char: "🏠", name: "house home", group: "travel" },
  { code: "1f4cd", char: "📍", name: "location pin place", group: "travel" },
  { code: "1f5fa", char: "🗺", name: "map", group: "travel" },
  { code: "1f54c", char: "🕌", name: "mosque", group: "travel" },
  { code: "1f3d4", char: "🏔", name: "mountain", group: "travel" },
];

export const STICKER_CODES = new Set(STICKERS.map((s) => s.code));

/** The sticker for an emoji character or a name like "thumbs up". */
export function findSticker(query: string): Sticker | undefined {
  const q = query.trim().toLowerCase();
  return STICKERS.find((s) => s.char === query.trim() || s.code === q) ?? STICKERS.find((s) => s.name === q) ?? STICKERS.find((s) => s.name.split(" ").includes(q)) ?? STICKERS.find((s) => s.name.includes(q));
}
